/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/../components/scene/SceneContent`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSceneAction`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useButtonSound`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useDialogueAnimation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/scene/SceneContent`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useSceneAction`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useButtonSound`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useDialogueAnimation`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/App${`?${string}` | `#${string}` | ''}` | `/../components/scene/SceneContent${`?${string}` | `#${string}` | ''}` | `/../hooks/useSceneAction${`?${string}` | `#${string}` | ''}` | `/../hooks/useButtonSound${`?${string}` | `#${string}` | ''}` | `/../hooks/useDialogueAnimation${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/../components/scene/SceneContent`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSceneAction`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useButtonSound`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useDialogueAnimation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
